
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sakura
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string Controls
        {
            get
            {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string START
        {
            get
            {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to SELECT.
        /// </summary>
        internal static string SELECT
        {
            get
            {
                return ResourceManager.GetString("SELECT", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string A
        {
            get
            {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string B
        {
            get
            {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to UP.
        /// </summary>
        internal static string UP
        {
            get
            {
                return ResourceManager.GetString("UP", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to DOWN.
        /// </summary>
        internal static string DOWN
        {
            get
            {
                return ResourceManager.GetString("DOWN", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to RIGHT.
        /// </summary>
        internal static string RIGHT
        {
            get
            {
                return ResourceManager.GetString("RIGHT", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to LEFT.
        /// </summary>
        internal static string LEFT
        {
            get
            {
                return ResourceManager.GetString("LEFT", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Cannot have the same key for multiple buttons..
        /// </summary>
        internal static string Cannothavethesamekey
        {
            get
            {
                return ResourceManager.GetString("Cannothavethesamekey", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Controls saved successfully..
        /// </summary>
        internal static string Controlssavedsuccessfully
        {
            get
            {
                return ResourceManager.GetString("Controlssavedsuccessfully", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Controls saved..
        /// </summary>
        internal static string Controlssaved
        {
            get
            {
                return ResourceManager.GetString("Controlssaved", resourceCulture);
            }
        }































        /// <summary>
        ///   Looks up a localized string similar to ASCII color:.
        /// </summary>
        internal static string ErrorloadingsettingsexMessage
        {
            get
            {
                return ResourceManager.GetString("ErrorloadingsettingsexMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ASCII color:.
        /// </summary>
        internal static string Roms
        {
            get
            {
                return ResourceManager.GetString("Roms", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ASCII color:.
        /// </summary>
        internal static string ASCIIcolor
        {
            get
            {
                return ResourceManager.GetString("ASCIIcolor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Background color:.
        /// </summary>
        internal static string Backgroundcolor
        {
            get
            {
                return ResourceManager.GetString("Backgroundcolor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string Black
        {
            get
            {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue
        {
            get
            {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BrightBlue.
        /// </summary>
        internal static string BrightBlue
        {
            get
            {
                return ResourceManager.GetString("BrightBlue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BrightCyan.
        /// </summary>
        internal static string BrightCyan
        {
            get
            {
                return ResourceManager.GetString("BrightCyan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BrightGreen.
        /// </summary>
        internal static string BrightGreen
        {
            get
            {
                return ResourceManager.GetString("BrightGreen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BrightMagenta.
        /// </summary>
        internal static string BrightMagenta
        {
            get
            {
                return ResourceManager.GetString("BrightMagenta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BrightRed.
        /// </summary>
        internal static string BrightRed
        {
            get
            {
                return ResourceManager.GetString("BrightRed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BrightYellow.
        /// </summary>
        internal static string BrightYellow
        {
            get
            {
                return ResourceManager.GetString("BrightYellow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        internal static string Brown
        {
            get
            {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel
        {
            get
            {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Choose color.
        /// </summary>
        internal static string ChooseColor
        {
            get
            {
                return ResourceManager.GetString("ChooseColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        internal static string Cyan
        {
            get
            {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DarkGray.
        /// </summary>
        internal static string DarkGray
        {
            get
            {
                return ResourceManager.GetString("DarkGray", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date
        {
            get
            {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Delete: .
        /// </summary>
        internal static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Disable ASCII.
        /// </summary>
        internal static string DisableASCII
        {
            get
            {
                return ResourceManager.GetString("DisableASCII", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disable colored hotkey information.
        /// </summary>
        internal static string Disablecoloredhotkeyinformation
        {
            get
            {
                return ResourceManager.GetString("Disablecoloredhotkeyinformation", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Enable detailed logging.
        /// </summary>
        internal static string Enabledetailedlogging
        {
            get
            {
                return ResourceManager.GetString("Enabledetailedlogging", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error
        {
            get
            {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string Errors
        {
            get
            {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Error saving settings:.
        /// </summary>
        internal static string ErrorsavingsettingsexMessage
        {
            get
            {
                return ResourceManager.GetString("ErrorsavingsettingsexMessage", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit
        {
            get
            {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit?.
        /// </summary>
        internal static string Exit_
        {
            get
            {
                return ResourceManager.GetString("Exit?", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        internal static string FatalError
        {
            get
            {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File/Folder:.
        /// </summary>
        internal static string File_Folder
        {
            get
            {
                return ResourceManager.GetString("File/Folder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Focus background color:.
        /// </summary>
        internal static string Focusbackgroundcolor
        {
            get
            {
                return ResourceManager.GetString("Focusbackgroundcolor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Focus text color:.
        /// </summary>
        internal static string Focustextcolor
        {
            get
            {
                return ResourceManager.GetString("Focustextcolor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to folder/file path.
        /// </summary>
        internal static string Folderslashfilepath
        {
            get
            {
                return ResourceManager.GetString("Folderslashfilepath", resourceCulture);
            }
        }





        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        internal static string Gray
        {
            get
            {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green
        {
            get
            {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        internal static string Help
        {
            get
            {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hide text cursor.
        /// </summary>
        internal static string Hidetextcursor
        {
            get
            {
                return ResourceManager.GetString("Hidetextcursor", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Hide text cursor.
        /// </summary>
        internal static string Usesystemconsole
        {
            get
            {
                return ResourceManager.GetString("Usesystemconsole", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to Hotkey text color:.
        /// </summary>
        internal static string Hotkeytextcolor
        {
            get
            {
                return ResourceManager.GetString("Hotkeytextcolor", resourceCulture);
            }
        }




        /// <summary>
        ///   Looks up a localized string similar to Invalid file.
        /// </summary>
        internal static string InvalidFile
        {
            get
            {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid file/folder path..
        /// </summary>
        internal static string Invalidfile_folderpath
        {
            get
            {
                return ResourceManager.GetString("Invalidfile/folderpath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid folder.
        /// </summary>
        internal static string InvalidFolder
        {
            get
            {
                return ResourceManager.GetString("InvalidFolder", resourceCulture);
            }
        }





        /// <summary>
        ///   Looks up a localized string similar to Invalid path..
        /// </summary>
        internal static string Invalidpath
        {
            get
            {
                return ResourceManager.GetString("Invalidpath", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Log
        {
            get
            {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log Path:.
        /// </summary>
        internal static string LogPath
        {
            get
            {
                return ResourceManager.GetString("LogPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log path cannot be empty..
        /// </summary>
        internal static string Logpathcannotbeempty
        {
            get
            {
                return ResourceManager.GetString("Logpathcannotbeempty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        internal static string Magenta
        {
            get
            {
                return ResourceManager.GetString("Magenta", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to Missing Directory.
        /// </summary>
        internal static string MissingDirectory
        {
            get
            {
                return ResourceManager.GetString("MissingDirectory", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No
        {
            get
            {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }




        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK
        {
            get
            {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }





        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red
        {
            get
            {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to Select config file path.
        /// </summary>
        internal static string Selectconfigfilepath
        {
            get
            {
                return ResourceManager.GetString("Selectconfigfilepath", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to Selected file does not exist..
        /// </summary>
        internal static string Selectedfiledoesnotexist
        {
            get
            {
                return ResourceManager.GetString("Selectedfiledoesnotexist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selected folder does not exist..
        /// </summary>
        internal static string Selectedfolderdoesnotexist
        {
            get
            {
                return ResourceManager.GetString("Selectedfolderdoesnotexist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select filename for the config file..
        /// </summary>
        internal static string Selectfilenamefortheconfigfile
        {
            get
            {
                return ResourceManager.GetString("Selectfilenamefortheconfigfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select filename for the log file..
        /// </summary>
        internal static string Selectfilenameforthelogfile
        {
            get
            {
                return ResourceManager.GetString("Selectfilenameforthelogfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        internal static string Selectfolder
        {
            get
            {
                return ResourceManager.GetString("Selectfolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select log file path.
        /// </summary>
        internal static string Selectlogfilepath
        {
            get
            {
                return ResourceManager.GetString("Selectlogfilepath", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings
        {
            get
            {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings Path:.
        /// </summary>
        internal static string SettingsPath
        {
            get
            {
                return ResourceManager.GetString("SettingsPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings path cannot be empty..
        /// </summary>
        internal static string Settingspathcannotbeempty
        {
            get
            {
                return ResourceManager.GetString("Settingspathcannotbeempty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings saved.
        /// </summary>
        internal static string Settingssaved
        {
            get
            {
                return ResourceManager.GetString("Settingssaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings saved successfully.
        /// Some changes will take effect after restarting..
        /// </summary>
        internal static string Settingssavedsuccessfully
        {
            get
            {
                return ResourceManager.GetString("Settingssavedsuccessfully", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to Start: .
        /// </summary>
        internal static string Start
        {
            get
            {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }




        /// <summary>
        ///   Looks up a localized string similar to Start:.
        /// </summary>
        internal static string StartSettingsCurrentControlsStartDownload
        {
            get
            {
                return ResourceManager.GetString("StartSettingsCurrentControlsStartDownload", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to Stop: .
        /// </summary>
        internal static string Stop
        {
            get
            {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }




        /// <summary>
        ///   Looks up a localized string similar to Text color:.
        /// </summary>
        internal static string Textcolor
        {
            get
            {
                return ResourceManager.GetString("Textcolor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected error:.
        /// </summary>
        internal static string Unexpectederror
        {
            get
            {
                return ResourceManager.GetString("Unexpectederror", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown
        {
            get
            {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string Unknownerror
        {
            get
            {
                return ResourceManager.GetString("Unknownerror", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string White
        {
            get
            {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes
        {
            get
            {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }


    }
}
